// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Counter } from "./tables/Counter.sol";
import { Function } from "./tables/Function.sol";
import { Slot } from "./tables/Slot.sol";
import { ContractCounter } from "./tables/ContractCounter.sol";
