// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IContractSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IContractSystem {
  function app__deployContract(bytes32[] memory functions) external returns (uint32);

  function app__executeFunction(uint32 contractId, uint32 functionId, bytes32[] memory params) external returns (bool);
}
